stanford university: United States
massachusetts institute of technology: United States
mit: United States
carnegie mellon university: United States
university of california berkeley: United States
harvard university: United States
princeton university: United States
yale university: United States
columbia university: United States
cornell university: United States
google: United States
openai: United States
nvidia: United States
deepmind: United Kingdom
university of oxford: United Kingdom
university of cambridge: United Kingdom
tsinghua university: China
peking university: China
shanghai jiao tong university: China
zhejiang university: China
fudan university: China
beihang university: China
harbin institute of technology: China
university of tokyo: Japan
eth zurich: Switzerland
